import './style.css';import {sample} from './sample.js';
const app=document.getElementById('app');let view='overview',period=28,chartMode='distance',logFilter='All',modal=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const local=()=>{try{return JSON.parse(localStorage.getItem('five-am-runs')||'[]')}catch{return []}};
/* public demo log (Supabase, demo rows only) with the baked sample as offline fallback; personal entries stay in localStorage */
const SB_URL='https://iljapbrjcxhtymtkiuea.supabase.co',SB_KEY='sb_publishable_bKtD9c5Q0GzMFNOZQ58z8A_WCIxbRt8';
let remote=[],remoteOk=false;
const base=()=>remoteOk?remote:sample;
const runs=()=>[...local(),...base()].sort((a,b)=>b.date.localeCompare(a.date));
async function loadRemote(){try{const r=await fetch(SB_URL+'/rest/v1/fiveam_runs?select=*&order=date.desc',{headers:{apikey:SB_KEY}});if(!r.ok)throw 0;const rows=await r.json();if(!Array.isArray(rows))throw 0;remote=rows;remoteOk=true}catch{remoteOk=false}render()}
const date=d=>new Date(d+'T00:00:00');const fmt=d=>date(d).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'});
const pace=r=>r.km>0?`${Math.floor(r.minutes/r.km)}:${String(Math.round((r.minutes/r.km%1)*60)).padStart(2,'0')}`:'—';
const sum=r=>r.reduce((n,x)=>n+x.km,0),avg=r=>r.length?sum(r)/r.length:0;
function areaChart(data,mode){let vals=data.map(r=>mode==='distance'?r.km:Number((r.minutes/r.km).toFixed(2))).reverse(),w=840,h=260,top=28,bot=220,step=w/Math.max(vals.length-1,1),min=mode==='pace'?4:0,max=mode==='pace'?9:Math.max(10,Math.ceil(Math.max(0,...vals)/2)*2),y=v=>bot-((v-min)/(max-min))*(bot-top),pts=vals.map((v,i)=>[i*step,y(v)]);let line=pts.map(([x,z],i)=>`${i?'L':'M'}${x.toFixed(1)},${z.toFixed(1)}`).join(' '),fill=line+` L${w},${bot} L0,${bot} Z`;return `<div class="chart-wrap"><svg class="chart" viewBox="0 0 ${w} ${h}" preserveAspectRatio="none" role="img" aria-label="${mode==='distance'?'Distance in kilometers':'Pace in minutes per kilometer'} for ${data.length} demo runs">${[0,.25,.5,.75,1].map(n=>`<line x1="0" x2="${w}" y1="${top+(bot-top)*n}" y2="${top+(bot-top)*n}" class="gridline"/>`).join('')}<path d="${fill}" class="area"/><path d="${line}" class="line"/>${pts.map(([x,z],i)=>`<circle cx="${x}" cy="${z}" r="${i===pts.length-1?5:2}" class="chart-dot"><title>${esc(data[data.length-1-i]?.date)}: ${mode==='distance'?vals[i]+' km':pace(data[data.length-1-i])+'/km'}</title></circle>`).join('')}</svg><div class="chart-axis"><span>OLDER</span><span>RECENT</span></div></div>`}
function calendar(){let latest=date(runs()[0]?.date||'2026-09-27');let today=new Date();if(today>latest)latest=today;let first=new Date(latest);first.setDate(first.getDate()-83);first.setDate(first.getDate()-(first.getDay()+6)%7);let days=84, byDate=new Map(runs().map(r=>[r.date,r]));let cells=Array.from({length:days},(_,i)=>{let dt=new Date(first);dt.setDate(first.getDate()+i);let key=`${dt.getFullYear()}-${String(dt.getMonth()+1).padStart(2,'0')}-${String(dt.getDate()).padStart(2,'0')}`;let r=byDate.get(key),v=r?Math.min(4,Math.max(1,Math.ceil(r.km/2))):0;return `<div class="heat-cell level-${v}" title="${key}: ${r?`${r.km} km, ${pace(r)}/km (${r.demo?'sample':'your entry'})`:'No entry'}" aria-label="${key}: ${r?`${r.km} kilometers (${r.demo?'sample':'your entry'})`:'no entry'}"></div>`}).join('');return `<div class="heat-scroll"><div class="heat-layout"><div class="heat-days"><span>M</span><span>W</span><span>F</span></div><div class="heat-grid">${cells}</div></div><div class="heat-months"><span>${first.toLocaleString('en-US',{month:'short'}).toUpperCase()}</span><span>${new Date(first.getFullYear(),first.getMonth()+1,1).toLocaleString('en-US',{month:'short'}).toUpperCase()}</span><span>${new Date(first.getFullYear(),first.getMonth()+2,1).toLocaleString('en-US',{month:'short'}).toUpperCase()}</span></div></div>`}
function longestStreak(){let dates=new Set(runs().map(r=>r.date));let best=0;for(let key of dates){let d=date(key),length=0;while(dates.has(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`)){length++;d.setDate(d.getDate()-1)}best=Math.max(best,length)}return best}function metrics(){let r=runs().slice(0,period),best=r.reduce((a,b)=>!a||b.km>a.km?b:a,null),quick=r.reduce((a,b)=>!a||b.minutes/b.km<a.minutes/a.km?b:a,null);return [{label:'DISTANCE',value:sum(r).toFixed(1),unit:'km',note:`Last ${period} logged runs`},{label:'AVERAGE RUN',value:avg(r).toFixed(1),unit:'km',note:'Distance per session'},{label:'LONGEST',value:best?.km.toFixed(1)||'—',unit:'km',note:best?fmt(best.date):'No entries'},{label:'QUICKEST PACE',value:quick?pace(quick):'—',unit:'/km',note:quick?fmt(quick.date):'No entries'}]}
function overview(){let r=runs(),shown=r.slice(0,period);return `<section class="headline"><div class="headline-inner"><div class="overline">A RUNNING JOURNAL <span> / </span> THE EARLY HOURS</div><h1>Before the world<br><i>wakes up.</i></h1><div class="hero-bottom"><p>Some mornings you go far. Some you just go. Keep a record of both.</p><div class="hero-emblem" aria-hidden="true"><span>05<span class="colon">:</span>00</span><small>THE EARLY HOURS CLUB</small></div></div></div><div class="stripe"></div></section><section class="overview-body"><div class="section-heading"><div><span class="overline ink">01 / THE NUMBERS</span><h2>The work adds up.</h2></div><div class="segmented" role="group" aria-label="Period"><button data-period="14" class="${period===14?'on':''}" aria-pressed="${period===14}">14 RUNS</button><button data-period="28" class="${period===28?'on':''}" aria-pressed="${period===28}">28 RUNS</button><button data-period="60" class="${period===60?'on':''}" aria-pressed="${period===60}">ALL</button></div></div><div class="metric-grid">${metrics().map((m,i)=>`<div class="metric"><span class="metric-num">0${i+1} / ${m.label}</span><div><strong>${m.value}</strong><span class="unit">${m.unit}</span></div><small>${m.note}</small></div>`).join('')}</div><section class="data-panel"><div class="panel-head"><div><span class="overline ink">02 / PACE & DISTANCE</span><h2>One morning at a time.</h2></div><div class="chart-toggle" role="group" aria-label="Chart measure"><button data-chart="distance" class="${chartMode==='distance'?'on':''}" aria-pressed="${chartMode==='distance'}">DISTANCE</button><button data-chart="pace" class="${chartMode==='pace'?'on':''}" aria-pressed="${chartMode==='pace'}">PACE</button></div></div>${areaChart(shown,chartMode)}<div class="chart-key"><span><i></i> ${chartMode==='distance'?'KILOMETERS PER RUN':'MINUTES / KILOMETER'}</span><span>${shown.length} RUNS</span></div></section><section class="heat-section"><div class="panel-head"><div><span class="overline ink">03 / THE PATTERN</span><h2>Show up again.</h2></div><p>Each square is a date. Hover for its run.<br>Blank is part of the picture, too.</p></div>${calendar()}<div class="streak-caption"><strong>${longestStreak()} days</strong><span>LONGEST RECORDED STREAK</span></div><div class="legend"><span>LESS</span>${[0,1,2,3,4].map(v=>`<i class="level-${v}"></i>`).join('')}<span>MORE</span></div></section><section class="recent-section"><div class="section-heading"><div><span class="overline ink">04 / THE LOGBOOK</span><h2>Latest entries.</h2></div><a class="plain-link" href="#log">VIEW THE FULL LOG ↗</a></div><div class="run-list">${r.slice(0,5).map(runRow).join('')}</div></section></section>`}
function runRow(r){return `<div class="run-row"><span class="run-date">${fmt(r.date)}</span><div class="run-title"><strong>${esc(r.title)}</strong><small>${esc(r.type.toUpperCase())} · ${r.demo?'SAMPLE ENTRY':'YOUR LOCAL ENTRY'}</small></div><strong class="row-dist">${Number(r.km).toFixed(1)} <small>KM</small></strong><span class="row-pace">${pace(r)} <small>/ KM</small></span></div>`}
function log(){let filtered=runs().filter(r=>logFilter==='All'||(logFilter==='Mine'?!r.demo:r.type===logFilter));return `<section class="log-page"><div class="log-header"><div><span class="overline ink">THE RUN ARCHIVE</span><h1>The logbook<span>.</span></h1><p>Nothing here is a score. It's a record of getting out the door.</p></div><div class="log-stamp">FIVE / AM <span>EST. FOR THE NEXT RUN</span></div></div><div class="filter-bar" role="group" aria-label="Filter runs">${['All','Easy','Tempo','Long','Recovery','Mine'].map(f=>`<button data-filter="${f}" class="${f===logFilter?'on':''}" aria-pressed="${f===logFilter}">${f.toUpperCase()} <span>${f==='All'?runs().length:f==='Mine'?local().length:runs().filter(r=>r.type===f).length}</span></button>`).join('')}</div><div class="run-head"><span>DATE</span><span>SESSION</span><span>DISTANCE</span><span>PACE</span></div><div class="run-list">${filtered.length?filtered.map(runRow).join(''):`<div class="no-runs"><strong>No runs here yet.</strong><p>Add your first run to start this page.</p><button class="primary" id="empty-log">LOG A RUN ↗</button></div>`}</div></section>`}
function about(){return `<section class="about"><div class="about-lead"><span class="overline">FIVE / AM · A NOTE TO SELF</span><h1>Run your own<br><em>race.</em></h1><p>A place for early starts, short loops, breakthroughs, and days that simply count because you went.</p></div><div class="about-columns"><div><span>01 / A JOURNAL, NOT A COMPETITION</span><h2>Remember the feeling. Measure the work.</h2></div><div><p>Log a run with its date, distance, time, and a few words. Watch your own pattern take shape in charts and on the calendar.</p><p>This is a prototype with sample entries for layout and interaction. The preview numbers do not represent the site owner's real performance. Your entries save only to this browser - clear storage and they are gone. The live demo log is sample data, not anyone's real running.</p><button class="primary" id="about-log">LOG A RUN ↗</button></div></div></section>`}
function modalHtml(){return `<div class="modal-layer" id="modal-layer"><div class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-heading"><div class="modal-top"><span class="overline ink">A NEW ENTRY / LOCAL ONLY</span><button id="modal-close" aria-label="Close dialog">×</button></div><h2 id="modal-heading">Log a run.</h2><p>For now, this run stays only in this browser.</p><form id="run-form"><label>DATE <input type="date" name="date" required></label><label>WHAT WOULD YOU CALL IT? <input type="text" name="title" placeholder="The quiet loop" maxlength="60" required></label><div class="form-grid"><label>DISTANCE / KM <input type="number" name="km" min="0.1" max="300" step="0.1" placeholder="5.0" required></label><label>TIME / MINUTES <input type="number" name="minutes" min="1" max="3000" step="0.1" placeholder="30.0" required></label></div><label>TYPE <select name="type"><option>Easy</option><option>Tempo</option><option>Long</option><option>Recovery</option></select></label><button type="submit" class="primary">SAVE THIS RUN ↗</button></form></div></div>`}
function shell(content){return `<div class="site"><header><a href="#overview" class="logo" aria-label="Five AM overview"><span>FIVE<span class="logo-slash">/</span>AM</span><small>RUN JOURNAL</small></a><nav aria-label="Main"><a href="#overview" class="${view==='overview'?'active':''}">OVERVIEW</a><a href="#log" class="${view==='log'?'active':''}">THE LOG</a><a href="#about" class="${view==='about'?'active':''}">ABOUT</a></nav><button class="header-add" id="header-add"><span>+</span> LOG A RUN</button></header><main>${content}</main><footer><a class="footer-logo" href="#overview">FIVE / AM</a><span>EVERY ENTRY IS A STARTING LINE.</span><span>© 2026 · ${remoteOk?'DEMO LOG · LIVE':'PROTOTYPE / SAMPLE DATA'}</span></footer></div>${modal?modalHtml():''}`}
function render(){view=location.hash.slice(1)||'overview';if(!['overview','log','about'].includes(view))view='overview';app.innerHTML=shell(view==='log'?log():view==='about'?about():overview());bind()}
function open(){modal=true;app.insertAdjacentHTML('beforeend',modalHtml());bindModal();document.getElementById('modal-close').focus();document.body.style.overflow='hidden'}
function close(){modal=false;document.getElementById('modal-layer')?.remove();document.body.style.overflow=''}
function bindModal(){document.getElementById('modal-close')?.addEventListener('click',close);document.getElementById('modal-layer')?.addEventListener('click',e=>{if(e.target.id==='modal-layer')close()});document.getElementById('run-form')?.addEventListener('submit',async e=>{e.preventDefault();let d=new FormData(e.target),km=Number(d.get('km')),minutes=Number(d.get('minutes'));if(!Number.isFinite(km)||!Number.isFinite(minutes)||km<.1||minutes<1)return;let run={id:'own-'+Date.now(),date:d.get('date'),title:String(d.get('title')).trim(),km,minutes,type:d.get('type'),demo:false};localStorage.setItem('five-am-runs',JSON.stringify([run,...local()]))close();view='log';location.hash='log';render()})}
function bind(){document.querySelectorAll('#header-add,#empty-log,#about-log').forEach(b=>b?.addEventListener('click',open));document.querySelectorAll('[data-period]').forEach(b=>b.addEventListener('click',()=>{period=Number(b.dataset.period);render()}));document.querySelectorAll('[data-chart]').forEach(b=>b.addEventListener('click',()=>{chartMode=b.dataset.chart;render()}));document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{logFilter=b.dataset.filter;render()}));if(modal)bindModal()}
window.addEventListener('hashchange',()=>{close();render();window.scrollTo(0,0)});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal)close()});render();loadRemote();
